### PR TITLE
Adding timeout and changing port for mailtrap

### PR DESCRIPTION
**Pull request by Tegarassen**
Added a new port as it more recommended for mailtrap and more reliable than port 25 : https://mailtrap.io/blog/smtp-ports-25-465-587-used-for/ Added a timeout as with rails 7 in certain situation mails took more than 5 second to be sent and were getting a timeout error Also added enable_starttls_auto as it  detects if STARTTLS is enabled in your SMTP server and starts to use it: https://guides.rubyonrails.org/action_mailer_basics.html

We tested and it is working fine on our end.

### CODE REVIEW

**Comment by tpope** [comment]
I don't like replacing `first_inbox['smtp_ports'][0]` with a hard-coded integer. Can we use `first_inbox['smtp_ports'].last` instead?

**Comment by Tegarassen** [comment]
> I don't like replacing `first_inbox['smtp_ports'][0]` with a hard-coded integer. Can we use `first_inbox['smtp_ports'].last` instead?

yes fine on my end

**Comment by tpope** [comment]
`first_inbox` has been replaced by `inbox`; you'll need to resolve that in the merge conflict.

**Comment by Tegarassen** [comment]
> `first_inbox` has been replaced by `inbox`; you'll need to resolve that in the merge conflict.

done

**Comment by Tegarassen** [comment]
Hello @tpope is there any issue why we can't this pr please ?

**Comment by tpope** [comment]
Can we drop the timeouts? They feel like an orthogonal concern.

**Comment by Tegarassen** [comment]
> Can we drop the timeouts? They feel like an orthogonal concern.

yes we can drop the timeout for now, but with rails 7 we had some timeout issue which rises from time to time. If we get this issue again I will do another pr to add the time out

**Pull request merged**
